---
title: "Main"
output: html_document
date: "2025-03-30"
---

```{r}
source("code/setup.R")
```

```{r}
data_CR_PIB_long <- data_CR_PIB %>% 
  pivot_longer(cols = everything(), names_to = "año", values_to = "valor") %>% 
  mutate(fecha = ymd(paste0(año, "-01-01")))  # Creamos fecha con formato AAAA-01-01

data_CR_PIB_long$valor <- as.numeric(data_CR_PIB_long$valor)

ggplot(data_CR_PIB_long, aes(x = fecha, y = valor)) +
  geom_line(color = "#CD5555", linewidth = 1) +
  geom_point(color = "black", size = 1.5) +
  labs(title = "Valor del PIB de Costa Rica según el año",
       x = "Años",
       y = "Valor") +
  scale_x_date(date_labels = "%Y", 
               date_breaks = "3 year",
               expand = expansion(mult = 0.1)) +  # Pequeño margen en los extremos
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5),)
```

```{r}
data_CR_PIB_variacion_long <- data_CR_Variacion_PIB %>% 
  pivot_longer(cols = everything(), names_to = "año", values_to = "valor") %>% 
  mutate(fecha = ymd(paste0(año, "-01-01")))  # Creamos fecha con formato AAAA-01-01

data_CR_PIB_variacion_long$valor <- as.numeric(data_CR_PIB_variacion_long$valor)

ggplot(data_CR_PIB_variacion_long, aes(x = fecha, y = valor)) +
  geom_line(color = "#CD5555", linewidth = 1) +
  geom_point(color = "black", size = 1.5) +
  labs(title = "Variación del PIB de Costa Rica según año",
       x = "Años",
       y = "Valor (%)") +
  scale_x_date(date_labels = "%Y", 
               date_breaks = "3 year",
               expand = expansion(mult = 0.1)) +  # Pequeño margen en los extremos
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5),)
```

